In [4]:
# import library
import numpy as np
import pandas as pd

1. Array

In [131]:
car = np.array(["Toyoty","Mitsubishi","Skoda","Fiat","Mini","VW"])
print(type(car))
print(car.dtype)

<class 'numpy.ndarray'>
<U10


2. np.asarray function

In [132]:
model = ["Aygo","Space Star","Citigo","500","Cooper","Up!"]
volumn = (1000,1200,1000,929,900,1500)
model = np.asarray(model)
volumn = np.asarray(volumn)
print(model)
print(volumn)

['Aygo' 'Space Star' 'Citigo' '500' 'Cooper' 'Up!']
[1000 1200 1000  929  900 1500]


3. np.zero(), np.ones() function

In [133]:
arr_zeros = np.zeros(4)
arr_ones = np.ones(3, dtype=int)
print(arr_zeros, arr_ones)

[0. 0. 0. 0.] [1 1 1]


4. Accessing array

In [127]:
weight = np.random.randint(500, 1500, 6)
weight

array([1174,  688, 1117,  803,  753, 1004])

In [128]:
print(weight)
print(weight[1])
print(weight[-2])
print(weight[[1,3,4]])
print(weight[2:5])
print(weight[weight < 1000])

[1174  688 1117  803  753 1004]
688
753
[688 803 753]
[1117  803  753]
[688 803 753]


5.Adding element

In [129]:
co2 = np.array([99,95,95, 105, 19])
print(co2)
co2 = np.append(co2, [105])
print(co2)
co2 = np.insert(co2, 3, [90])
print(co2)

[ 99  95  95 105  19]
[ 99  95  95 105  19 105]
[ 99  95  95  90 105  19 105]


6. Deleting element

In [134]:
co2 = np.delete(co2, 5)
print(co2)

[ 99  95  95  90 105 105]


7. Sorting

In [135]:
print(np.sort(car))
print(np.sort(model))
print(np.sort(volumn))
print(np.sort(weight))
print(np.sort(co2))

['Fiat' 'Mini' 'Mitsubishi' 'Skoda' 'Toyoty' 'VW']
['500' 'Aygo' 'Citigo' 'Cooper' 'Space Star' 'Up!']
[ 900  929 1000 1000 1200 1500]
[ 688  753  803 1004 1117 1174]
[ 90  95  95  99 105 105]


8. Accessing DataFrame

In [137]:
cars = pd.read_csv('D:\HK7\RPython\SampleData\cars.csv')
cars.head()

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [136]:
cars[3:8]

Car    Model  Volume  Weight  CO2
3      Fiat      500     900     865   90
4      Mini   Cooper    1500    1140  105
5        VW      Up!    1000     929  105
6     Skoda    Fabia    1400    1109   90
7  Mercedes  A-Class    1500    1365   92

In [121]:
cars[['Car','CO2']]

Car  CO2
0       Toyoty   99
1   Mitsubishi   95
2        Skoda   95
3         Fiat   90
4         Mini  105
5           VW  105
6        Skoda   90
7     Mercedes   92
8         Ford   98
9         Audi   99
10     Hyundai   99
11      Suzuki  101
12        Ford   99
13       Honda   94
14      Hundai   97
15        Opel   97
16         BMW   99
17       Mazda  104
18       Skoda  104
19        Ford  105
20        Ford   94
21        Opel   99
22    Mercedes   99
23       Skoda   99
24       Volvo   99
25    Mercedes  102
26        Audi  104
27        Audi  114
28       Volvo  109
29         BMW  114
30    Mercedes  115
31       Volvo  117
32        Ford  104
33         BMW  108
34        Opel  109
35    Mercedes  120

In [122]:
cars.head(5)

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [123]:
cars.tail(3)

Car   Model  Volume  Weight  CO2
33       BMW     216    1600    1390  108
34      Opel  Zafira    1600    1405  109
35  Mercedes     SLK    2500    1395  120

9. Deleting data

In [124]:
#delete last row
print(cars.drop(cars.index[-1]).tail())

         Car    Model  Volume  Weight  CO2
30  Mercedes  E-Class    2100    1605  115
31     Volvo     XC70    2000    1746  117
32      Ford    B-Max    1600    1235  104
33       BMW      216    1600    1390  108
34      Opel   Zafira    1600    1405  109


In [125]:
cars['new_col'] = cars['Weight']
print(cars.columns)
del cars['new_col']
print(cars.columns)

Index(['Car', 'Model', 'Volume', 'Weight', 'CO2', 'new_col'], dtype='object')
Index(['Car', 'Model', 'Volume', 'Weight', 'CO2'], dtype='object')


10. Sorting data

In [126]:
print()